# Generated by Django 5.0.4 on 2024-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservocabulary',
            name='examples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uservocabulary',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
