# Generated by Django 5.0.4 on 2024-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='parts_of_speech',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='uservocabulary',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='PartOfSpeech',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
