# Generated by Django 5.0.4 on 2024-05-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_vocabulary', '0002_alter_uservocabulary_examples_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservocabulary',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
