# Generated by Django 5.0.4 on 2024-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_vocabulary', '0002_remove_word_parts_of_speech_remove_word_synonyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('locale', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
