# Generated by Django 5.0.4 on 2024-05-11 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0011_customuser_email_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_user.plan'),
        ),
    ]
